package proiectpbd;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public final class CautAutomobil extends javax.swing.JFrame {

	FerPrinc cautp = new FerPrinc();
	Connection conn = null;
	PreparedStatement pst = null;
	ResultSet rs = null;
	Color c = new Color(110, 170, 40);

	/** Creates new form CautPiesa */
	public CautAutomobil() {
		initComponents();
		setTitle("Cautare Automobil");
		conn = cautp.javaconnection();
		jTextField1.setVisible(false);
		jTextField2.setVisible(false);
		jTextField3.setVisible(false);
		jTextField4.setVisible(false);
		getContentPane().setBackground(c);
		checkBox1Selected();
		checkBox2Selected();
		checkBox3Selected();
		checkBox4Selected();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox1.setBackground(c);
		jCheckBox1.setText("Marca auto");

		jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox2.setBackground(c);
		jCheckBox2.setText("Model auto");

		jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox3.setBackground(c);
		jCheckBox3.setText("Carburant");

		jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox4.setBackground(c);
		jCheckBox4.setText("Pret");

		jLabel1.setFont(new java.awt.Font("Arial", 3, 14));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Cautare Automobil : ");

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proiectpbd/home-feature-search-icon.png"))); // NOI18N
		jButton1.setText("Cautare");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
						.createSequentialGroup().addGap(9, 9,
								9)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(76, 76, 76).addComponent(jButton1)
										.addGap(107, 107, 107))
								.addGroup(layout.createSequentialGroup().addGap(34, 34, 34).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE, 167,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jCheckBox2).addComponent(jCheckBox1)
												.addComponent(jCheckBox3).addComponent(jCheckBox4))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
												.addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
												.addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
												.addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
						.addGap(18, 18, 18).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(24, 24, 24)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(19, 19, 19)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox1).addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox2).addComponent(jTextField2,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox3)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox4).addComponent(jTextField4,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(40, 40, 40).addComponent(jButton1)).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(29, Short.MAX_VALUE)));

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width - 781) / 2, (screenSize.height - 428) / 2, 781, 428);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate,producator "
						+ "where codp=Piese_codp and codm=Masina_codm and idp=Producator_idp and "
						+ "marca=? and codp=? and den=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField2.getText());
				pst.setString(3, jTextField3.getText());
				pst.setString(4, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate "
						+ "where codp=Piese_codp and codm=Masina_codm and " + "marca=? and codp=? and den=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField2.getText());
				pst.setString(3, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate,producator "
						+ "where codp=Piese_codp and codm=Masina_codm and idp=Producator_idp and "
						+ "marca=? and codp=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField2.getText());
				pst.setString(3, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate,producator "
						+ "where codp=Piese_codp and codm=Masina_codm and idp=Producator_idp and "
						+ "marca=? and den=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField3.getText());
				pst.setString(3, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,producator "
						+ "where idp=Producator_idp and " + "codp=? and den=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField2.getText());
				pst.setString(2, jTextField3.getText());
				pst.setString(3, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate "
						+ "where codp=Piese_codp and codm=Masina_codm and " + "marca=? and codp=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField2.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate "
						+ "where codp=Piese_codp and codm=Masina_codm and " + "marca=? and den=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate,producator "
						+ "where codp=Piese_codp and codm=Masina_codm and idp=Producator_idp and "
						+ "marca=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				pst.setString(2, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese "
						+ "where codp=? and den=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField2.getText());
				pst.setString(2, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,producator "
						+ "where  idp=Producator_idp and " + "codp=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField2.getText());
				pst.setString(2, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,producator "
						+ "where idp=Producator_idp and " + "den=? and nume=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField3.getText());
				pst.setString(2, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,masina,compatibilitate "
						+ "where codp=Piese_codp and codm=Masina_codm and " + "marca=? ";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField1.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese "
						+ "where codp=?";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField2.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese "
						+ "where den=? ";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codp Cod_piesa,den Denumire,datafab Data_fabricatie,stoc Stoc,pret Pret from piese,producator "
						+ "where idp=Producator_idp and " + "nume=? ";
				pst = conn.prepareStatement(sql);
				pst.setString(1, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else {
			JOptionPane.showMessageDialog(null, "Nu ati selectat criteriul de cautare!");
		}

		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	public void checkBox1Selected() {
		jCheckBox1.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField1.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField1.setVisible(false);
					jTextField1.setText("");

				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox2Selected() {
		jCheckBox2.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField2.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField2.setVisible(false);
					jTextField2.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox3Selected() {
		jCheckBox3.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField3.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField3.setVisible(false);
					jTextField3.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox4Selected() {
		jCheckBox4.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField4.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField4.setVisible(false);
					jTextField4.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new CautAutomobil().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
}
