package proiectpbd;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class CautVanzare extends javax.swing.JFrame {

	FerPrinc cautv = new FerPrinc();
	Connection conn = null;
	PreparedStatement pst = null;
	ResultSet rs = null;
	Color c = new Color(110, 170, 40);

	/** Creates new form CautVanzare */
	public CautVanzare() {
		initComponents();
		setTitle("Cautare Vanzare");
		conn = cautv.javaconnection();
		jTextField1.setVisible(false);
		jTextField2.setVisible(false);
		jTextField3.setVisible(false);
		jTextField4.setVisible(false);
		getContentPane().setBackground(c);
		checkBox1Selected();
		checkBox2Selected();
		checkBox3Selected();
		checkBox4Selected();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jDateChooser1 = new com.toedter.calendar.JDateChooser();
		jDateChooser2 = new com.toedter.calendar.JDateChooser();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Perioada : ");

		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText(" _ ");

		jTable1.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proiectpbd/home-feature-search-icon.png"))); // NOI18N
		jButton1.setText("Cautare");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jDateChooser1.setDateFormatString("d-MM-yyyy");

		jDateChooser2.setDateFormatString("d-MM-yyyy");

		jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox1.setBackground(c);
		jCheckBox1.setText("Nume client");

		jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox2.setBackground(c);
		jCheckBox2.setText("Automobil");

		jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox3.setBackground(c);
		jCheckBox3.setText("Marca Auto");

		jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
		jCheckBox4.setBackground(c);
		jCheckBox4.setText("Producator");
		jCheckBox4.setVisible(false);

		jLabel3.setFont(new java.awt.Font("Arial", 3, 14));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Criteriul de cautare : ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
						.createSequentialGroup().addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout
										.createSequentialGroup().addGap(31, 31, 31).addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGap(18, 18, 18))
												.addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGap(20, 20, 20))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGap(20, 20, 20)))
										.addGap(25, 25, 25)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 109,
														Short.MAX_VALUE)
												.addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 109,
														Short.MAX_VALUE)
												.addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 109,
														Short.MAX_VALUE)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(48, 48, 48))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addContainerGap()
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(69, 69, 69))
								.addGroup(layout.createSequentialGroup().addGap(111, 111, 111).addComponent(jButton1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(341, Short.MAX_VALUE)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 134,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jDateChooser2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(40, 40, 40)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(24, 24, 24)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel1)
						.addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2)))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addComponent(jLabel3).addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox1).addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox2).addComponent(jTextField2,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox3)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox4).addComponent(jTextField4,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(38, 38, 38).addComponent(jButton1)).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(21, Short.MAX_VALUE)));

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width - 759) / 2, (screenSize.height - 417) / 2, 759, 417);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			String sql = "select distinct codf Cod_factura,nume Nume,pren Prenume,adr Adresa,den Piesa,cant Cantitate,datav Data_cumparare from piese,factura,vanzare,client "
					+ "where codp=Piese_codp and codf=Vanzare_codf and codc=Client_codc and "
					+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y')";
			pst = conn.prepareStatement(sql);
			// pst.setString(1,jTextField1.getText());
			// pst.setString(2,jTextField2.getText());
			Date data1 = jDateChooser1.getDate();
			String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
			Date data2 = jDateChooser2.getDate();
			String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
			pst.setString(1, data1String);
			pst.setString(2, data2String);
			rs = pst.executeQuery();
			jTable1.setModel(DbUtils.resultSetToTableModel(rs));
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}
		if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and den=? and marca=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField2.getText());
				pst.setString(5, jTextField3.getText());
				pst.setString(6, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and den=? and marca=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField2.getText());
				pst.setString(5, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and den=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField2.getText());
				pst.setString(5, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and marca=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField3.getText());
				pst.setString(5, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and den=? and marca=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField2.getText());
				pst.setString(5, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox2.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and den=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField2.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and marca=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				pst.setString(4, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and den=? and marca=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField2.getText());
				pst.setString(4, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and den=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField2.getText());
				pst.setString(4, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox3.isSelected() & jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and marca=? and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField3.getText());
				pst.setString(4, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox1.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and cli.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField1.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox2.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and den=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField2.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox3.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and marca=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField3.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jCheckBox4.isSelected()) {
			try {
				String sql = "select distinct codf Cod_factura,cli.nume Nume,pren Prenume,den Piesa,cant Cantitate,datav Data_vanzarii from masina,compatibilitate c,piese,factura f,vanzare,client cli,producator prod "
						+ "where Masina_codm=codm and c.Piese_codp=codp and codf=Vanzare_codf and codc=Client_codc and f.Piese_codp=codp and idp=Producator_idp and "
						+ "datav between str_to_date(?, '%d-%m-%Y') and str_to_date(?, '%d-%m-%Y') and prod.nume=?";
				pst = conn.prepareStatement(sql);
				Date data1 = jDateChooser1.getDate();
				String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
				Date data2 = jDateChooser2.getDate();
				String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
				pst.setString(1, data1String);
				pst.setString(2, data2String);
				pst.setString(3, jTextField4.getText());
				rs = pst.executeQuery();
				jTable1.setModel(DbUtils.resultSetToTableModel(rs));
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		} else if (jDateChooser1.getDate() == null | jDateChooser2.getDate() == null)
			JOptionPane.showMessageDialog(null, "Nu ati selectat intervalul de cautare!");
		// else {JOptionPane.showMessageDialog(null,"Nu ati selectat criteriul
		// de cautare!");}
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	public void checkBox1Selected() {
		jCheckBox1.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField1.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField1.setVisible(false);
					jTextField1.setText("");

				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox2Selected() {
		jCheckBox2.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField2.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField2.setVisible(false);
					jTextField2.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox3Selected() {
		jCheckBox3.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField3.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField3.setVisible(false);
					jTextField3.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	public void checkBox4Selected() {
		jCheckBox4.addItemListener(new ItemListener() {
			@Override
			public void itemStateChanged(ItemEvent e) {
				if (e.getStateChange() == ItemEvent.SELECTED) {
					jTextField4.setVisible(true);
				} else if (e.getStateChange() == ItemEvent.DESELECTED) {
					jTextField4.setVisible(false);
					jTextField4.setText("");
				}

				validate();
				repaint();
			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new CautVanzare().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private com.toedter.calendar.JDateChooser jDateChooser1;
	private com.toedter.calendar.JDateChooser jDateChooser2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
}
