/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectpbd;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author bL0nDu
 */
public class InsertFact extends javax.swing.JFrame {
FerPrinc  fact=new FerPrinc();
Connection conn=null;
PreparedStatement pst1=null,pst2=null,pst3=null,pst4=null,pst5=null;
ResultSet rs=null,rs1=null;
Color c=new Color(0,102,153);
    /**
     * Creates new form InsertFact
     */
    public InsertFact() {
        initComponents();
        setTitle("Inserare Factura");
        conn=fact.javaconnection(); 
        getContentPane().setBackground(c);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cod factura :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data vanzarii :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cod client :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nume client :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Prenume client :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adresa client :");

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proiectpbd/add.png"))); // NOI18N
        jButton1.setText("Inserare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("d-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-308)/2, (screenSize.height-382)/2, 308, 382);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int k=0;
 try{ 
     
    String sql4="select codc from client";
    //String sql5="select codf from vanzare";
    pst4=conn.prepareStatement(sql4);
    //pst5=conn.prepareStatement(sql5); 
    rs=pst4.executeQuery();
    //rs1=pst5.executeQuery();
     //System.out.println(rs.getString("codc")); 
    rs.beforeFirst();
    //rs1.beforeFirst();
    k=0;
    while(rs.next()){
     //System.out.println(rs.getString("codc"));
        if(rs.getString("codc").compareTo(jTextField5.getText())==0){
            k=1;}}
    /*while(rs.next()){
        if(rs1.getString("codf").compareTo(jTextField1.getText())==0){
            k=2;}} 
     if(k==2){
     String sql3="insert into factura (Piese_codp,Vanzare_codf,cant) values(?,?,?)";
     pst3=conn.prepareStatement(sql3); 
        pst3.setString(2,jTextField1.getText());
        pst3.setString(1,jTextField2.getText());
        pst3.setString(3,jTextField3.getText());
        pst3.execute();
    }*/
    if(k==1){
     String sql2="insert into vanzare (codf,datav,Client_codc) values(?,str_to_date(?, '%d-%m-%Y'),?)";
     //String sql3="insert into factura (Piese_codp,Vanzare_codf,cant) values(?,?,?)";
     pst2=conn.prepareStatement(sql2);
     //pst3=conn.prepareStatement(sql3); 
        pst2.setString(1,jTextField1.getText());
        //pst3.setString(2,jTextField1.getText());
        //pst3.setString(1,jTextField2.getText());
        //pst3.setString(3,jTextField3.getText());
        Date data1 = jDateChooser1.getDate();
        String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
        pst2.setString(2,data1String);
        pst2.setString(3,jTextField5.getText());
        pst2.execute();
       // pst3.execute();
    }
    if(k==0){
     String sql1="insert into client (codc,nume,pren,adr) values(?,?,?,?)";
     String sql2="insert into vanzare (codf,datav,Client_codc) values(?,str_to_date(?, '%d-%m-%Y'),?)";
    // String sql3="insert into factura (Piese_codp,Vanzare_codf,cant) values(?,?,?)";
     pst1=conn.prepareStatement(sql1);
     pst2=conn.prepareStatement(sql2);
     //pst3=conn.prepareStatement(sql3); 
        pst2.setString(1,jTextField1.getText());
        //pst3.setString(2,jTextField1.getText());
        //pst3.setString(1,jTextField2.getText());
        //pst3.setString(3,jTextField3.getText());
        Date data1 = jDateChooser1.getDate();
        String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
        pst2.setString(2,data1String);
        pst1.setString(1,jTextField5.getText());
        pst2.setString(3,jTextField5.getText());
        pst1.setString(2,jTextField6.getText());
        pst1.setString(3,jTextField7.getText());
        pst1.setString(4,jTextField8.getText());
        pst1.execute();
        pst2.execute();
        //pst3.execute();
    }
              
JOptionPane.showMessageDialog(null,"Inserare Reusita!");


jTextField1.setText("");
//jTextField2.setText("");
//jTextField3.setText("");
jDateChooser1.setCalendar(null);
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
   
dispose();
}catch(Exception e){JOptionPane.showMessageDialog(null,e);
System.out.println(k);}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
// TODO add your handling code here:
 /*   String enteredVal=jTextField5.getText();
    int ok=0;
    String query=null;
    if(!enteredVal.isEmpty()){
        query="SELECT COUNT(*) FROM client WHERE codc="+enteredVal+";";
        try (Statement stmt=conn.createStatement()){
            ResultSet rs=stmt.executeQuery(query);
            rs.next();
            ok=rs.getInt("COUNT(*)");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            System.out.println(query);
        }
        if(ok==1){
            query="SELECT * FROM client WHERE codc="+enteredVal+";";
            try (Statement stmt=conn.createStatement()){
                ResultSet rs=stmt.executeQuery(query);
                rs.next();
                jTextField6.setText(rs.getString("nume"));
                jTextField7.setText(rs.getString("pren"));
                jTextField8.setText(rs.getString("adr"));
                jTextField6.setEditable(false);
                jTextField7.setEditable(false);
                jTextField8.setEditable(false);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }else{
            jTextField6.setText(null);
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
        }
    }*/
}//GEN-LAST:event_jTextField5FocusLost

private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
// TODO add your handling code here:
    String enteredVal=jTextField5.getText();
    int ok=0;
    String query=null;
    if(!enteredVal.isEmpty()){
        query="SELECT COUNT(*) FROM client WHERE codc="+enteredVal+";";
        try (Statement stmt=conn.createStatement()){
            ResultSet rs=stmt.executeQuery(query);
            rs.next();
            ok=rs.getInt("COUNT(*)");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
           // System.out.println(query);
        }
        if(ok==1){
            query="SELECT * FROM client WHERE codc="+enteredVal+";";
            try (Statement stmt=conn.createStatement()){
                ResultSet rs=stmt.executeQuery(query);
                rs.next();
                jTextField6.setText(rs.getString("nume"));
                jTextField7.setText(rs.getString("pren"));
                jTextField8.setText(rs.getString("adr"));
                jTextField6.setEditable(false);
                jTextField7.setEditable(false);
                jTextField8.setEditable(false);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }else{
            jTextField6.setText(null);
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
            jTextField8.setEditable(true);
        }
    }
}//GEN-LAST:event_jTextField5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertFact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InsertFact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
