/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Raport.java
 *
 * Created on Nov 30, 2012, 5:01:17 PM
 */
package proiectpbd;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
/**
 *
 * @author Liviu
 */

public class Raport extends javax.swing.JFrame {

    FerPrinc rp=new FerPrinc();
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    Color c=new Color(0,102,153);

    /** Creates new form Raport */
    public Raport() {
        initComponents();
        setTitle("Raport Vanzari");
        conn=rp.javaconnection();
        getContentPane().setBackground(c);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Raport vanzari");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Perioada : ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proiectpbd/pdf_icon.png"))); // NOI18N
        jButton1.setText("Generare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("->");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectati Raport", "Marca", "Piese", "Producatori" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("d-MM-yyyy");

        jDateChooser2.setDateFormatString("d-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))))
                .addGap(28, 28, 28)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(63, 63, 63))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-453)/2, (screenSize.height-291)/2, 453, 291);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String selectie=(String)jComboBox1.getSelectedItem();
if(selectie=="Producatori" & jDateChooser1.getDate()!=null & jDateChooser2.getDate()!=null){
try{Date data1 = jDateChooser1.getDate();
    String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
    Date data2 = jDateChooser2.getDate();
    String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
    JasperDesign jd=JRXmlLoader.load("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report.jrxml");
    String sql="select p.nume,den,cant,datav,c.nume as ncli,pren from producator p,piese,vanzare,factura,client c where idp=Producator_idp and codp=Piese_codp and Vanzare_codf=codf and codc=Client_codc and datav between str_to_date('"+data1String+"', '%d-%m-%Y') and str_to_date('"+data2String+"', '%d-%m-%Y')";
    JRDesignQuery nq=new JRDesignQuery();
    nq.setText(sql);
    jd.setQuery(nq);
    JasperReport jr=JasperCompileManager.compileReport(jd);
    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
    JasperExportManager.exportReportToPdfFile(jp,"C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report.pdf");
    openPDF();
}    
catch(Exception e){JOptionPane.showMessageDialog(null,e);}
}else
    if(selectie=="Piese" & jDateChooser1.getDate()!=null & jDateChooser2.getDate()!=null){
    try{Date data1 = jDateChooser1.getDate();
    String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
    Date data2 = jDateChooser2.getDate();
    String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
    JasperDesign jd=JRXmlLoader.load("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report2.jrxml");
    String sql="select p.nume,den,cant,datav,c.nume as ncli,pren from producator p,piese,vanzare,factura,client c where idp=Producator_idp and codp=Piese_codp and Vanzare_codf=codf and codc=Client_codc and datav between str_to_date('"+data1String+"', '%d-%m-%Y') and str_to_date('"+data2String+"', '%d-%m-%Y')";
    JRDesignQuery nq=new JRDesignQuery();
    nq.setText(sql);
    jd.setQuery(nq);
    JasperReport jr=JasperCompileManager.compileReport(jd);
    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
    JasperExportManager.exportReportToPdfFile(jp,"C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report2.pdf");
    openPDF1();
}    
catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }else
    if(selectie=="Marca" & jDateChooser1.getDate()!=null & jDateChooser2.getDate()!=null){
    try{Date data1 = jDateChooser1.getDate();
    String data1String = String.format("%1$td-%1$tm-%1$tY", data1);
    Date data2 = jDateChooser2.getDate();
    String data2String = String.format("%1$td-%1$tm-%1$tY", data2);
    JasperDesign jd=JRXmlLoader.load("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\marca.jrxml");
    String sql="select marca,model,nume,den,cant,datav from producator,piese,vanzare,factura f,masina,compatibilitate c where idp=Producator_idp and codp=c.Piese_codp and codp=f.Piese_codp and Masina_codm=codm and Vanzare_codf=codf and datav between str_to_date('"+data1String+"', '%d-%m-%Y') and str_to_date('"+data2String+"', '%d-%m-%Y')";
    JRDesignQuery nq=new JRDesignQuery();
    nq.setText(sql);
    jd.setQuery(nq);
    JasperReport jr=JasperCompileManager.compileReport(jd);
    JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
    JasperExportManager.exportReportToPdfFile(jp,"C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\marca.pdf");
    openPDF2();
}    
catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }else
        if(jDateChooser1.getDate()==null | jDateChooser2.getDate()==null)
            {JOptionPane.showMessageDialog(null,"Nu ati selectat perioada!");}
        else
            if(selectie=="Selectati Raport"){JOptionPane.showMessageDialog(null,"Nu ati selectat raportul!");}
}  
public void openPDF(){
String selectie=(String)jComboBox1.getSelectedItem();
if(selectie=="Producatori"){
    try{
        File file=new File("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report.pdf");
        if(file.toString().endsWith(".pdf"))
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+file);
        else
        {
            Desktop dsk=Desktop.getDesktop();
            dsk.open(file);
        }
        
    }catch(Exception e){};

}//GEN-LAST:event_jButton1ActionPerformed
}


public void openPDF1(){
String selectie=(String)jComboBox1.getSelectedItem();
if(selectie=="Piese"){
    try{
        File file=new File("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\report2.pdf");
        if(file.toString().endsWith(".pdf"))
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+file);
        else
        {
            Desktop dsk=Desktop.getDesktop();
            dsk.open(file);
        }
        
    }catch(Exception e){};

}                                        
}

public void openPDF2(){
String selectie=(String)jComboBox1.getSelectedItem();
if(selectie=="Marca"){
    try{
        File file=new File("C:\\Users\\Liviu\\Documents\\Proiect PBD\\ProiectPBD\\Rapoarte\\marca.pdf");
        if(file.toString().endsWith(".pdf"))
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+file);
        else
        {
            Desktop dsk=Desktop.getDesktop();
            dsk.open(file);
        }
        
    }catch(Exception e){};

}                                        
}


private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Raport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
